#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/lg4l-linux" ]; then
	update-rc.d lg4l-linux defaults >/dev/null
	invoke-rc.d lg4l-linux start || exit $?
fi
# End automatically added section
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	if [ -e "/etc/udev/rules.d/z60_lg4l-linux.rules" ]; then
		echo "Preserving user changes to /etc/udev/rules.d/40-lg4l-linux.rules ..."
		if [ -e "/etc/udev/rules.d/40-lg4l-linux.rules" ]; then
			mv -f "/etc/udev/rules.d/40-lg4l-linux.rules" "/etc/udev/rules.d/40-lg4l-linux.rules.dpkg-new"
		fi
		mv -f "/etc/udev/rules.d/z60_lg4l-linux.rules" "/etc/udev/rules.d/40-lg4l-linux.rules"
	fi
fi
# End automatically added section
