#!/usr/bin/env python
 
#        +-----------------------------------------------------------------------------+
#        | GPL                                                                         |
#        +-----------------------------------------------------------------------------+
#        | Copyright (c) Brett Smith <tanktarta@blueyonder.co.uk>                      |
#        |                                                                             |
#        | This program is free software; you can redistribute it and/or               |
#        | modify it under the terms of the GNU General Public License                 |
#        | as published by the Free Software Foundation; either version 2              |
#        | of the License, or (at your option) any later version.                      |
#        |                                                                             |
#        | This program is distributed in the hope that it will be useful,             |
#        | but WITHOUT ANY WARRANTY; without even the implied warranty of              |
#        | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
#        | GNU General Public License for more details.                                |
#        |                                                                             |
#        | You should have received a copy of the GNU General Public License           |
#        | along with this program; if not, write to the Free Software                 |
#        | Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. |
#        +-----------------------------------------------------------------------------+

import sys
import pygtk
pygtk.require('2.0')
import gtk
import gobject
import gnomeapplet
import os
import gconf

# Tell GTK we are using threads
#gtk.gdk.threads_init()
gobject.threads_init()

# Allow running from local path
path = os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])), "..","main", "python")
if os.path.exists(path):
    sys.path.insert(0, path)

import gnome15.g15_applet as g15applet
import gnome15.g15_globals as pglobals
import gnome15.g15_setup as g15setup
import gnome15.g15_driver_manager as g15drivermanager

print "In applet script"

# bonobo factory of pycentrinoApplets
def g15_applet_factory(applet, iid, parent_window=None):
    print "Creating new applet",applet,iid,parent_window
#    applet.set_background_widget(applet)
    app = g15applet.G15Applet(applet,iid,parent_window)
    if parent_window != None:
        parent_window.connect("delete-event", shutdown, app)
    else:
        applet.connect("delete-event", stop, app)
	return True
    
def stop(window, evt, applet):
    print "Stopping applet"
    if applet.service.plugins.get_active():
        applet.service.plugins.deactivate()
    if applet.service.plugins.get_started():
        applet.service.plugins.destroy()
    
def shutdown(window, evt, applet):
    print "Shutting down runtime"
    stop(window, evt, applet)
    gtk.main_quit()
   
if g15drivermanager.get_configured_driver("-c" in sys.argv) != None:
    if len(sys.argv) > 1 and "-w" in sys.argv:
        main_window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        main_window.set_title("Gnome15") 
        main_window.set_icon_from_file(pglobals.image_dir + "/g15key.png")
        app = gnomeapplet.Applet()
        g15_applet_factory(app, None, parent_window=main_window)
        app.reparent(main_window)
        main_window.show_all()
        gtk.main()
    else:
        if __name__ == '__main__':
            gnomeapplet.bonobo_factory("OAFIID:GNOME_G15Applet_Factory",
                                        g15applet.G15Applet.__gtype__, 
                                        "gnome15", "0", g15_applet_factory)