.\" Process this file with
.\" groff -man -Tascii g15-indicator.1
.\"
.TH g15-indicator 1
.SH NAME
g15-systemtray \- Starts a system tray icon for Gnome15 desktop service
.SH SYNOPSIS
.B g15-systemtray 
.SH DESCRIPTION
.B g15-systemtray
Gnome15 is a suite of applications and plugins that provide
integration of the Logitech G series keyboards into the 
GNOME desktop environment.

This application starts an Indicator allowing control and
monitoring of the Gnome15 desktop service. 
.SH AUTHOR
Brett Smith <tanktarta@blueyonder.co.uk>
.SH "SEE ALSO"
.BR g15-config (1),
.BR g15-desktop-service (1)
.BR g15-indicator (1)