#!/usr/bin/env python
 
#        +-----------------------------------------------------------------------------+
#        | GPL                                                                         |
#        +-----------------------------------------------------------------------------+
#        | Copyright (c) Brett Smith <tanktarta@blueyonder.co.uk>                      |
#        |                                                                             |
#        | This program is free software; you can redistribute it and/or               |
#        | modify it under the terms of the GNU General Public License                 |
#        | as published by the Free Software Foundation; either version 2              |
#        | of the License, or (at your option) any later version.                      |
#        |                                                                             |
#        | This program is distributed in the hope that it will be useful,             |
#        | but WITHOUT ANY WARRANTY; without even the implied warranty of              |
#        | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
#        | GNU General Public License for more details.                                |
#        |                                                                             |
#        | You should have received a copy of the GNU General Public License           |
#        | along with this program; if not, write to the Free Software                 |
#        | Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. |
#        +-----------------------------------------------------------------------------+

import sys
import os

# Allow running from local path
path = os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])), "..","main", "python")
if os.path.exists(path):
    sys.path.insert(0, path)

import gnome15.g15_config
import gnome15.g15_globals as pglobals

if __name__ == '__main__':

    import optparse
    parser = optparse.OptionParser()
    parser.add_option("-l", "--local", action="store_true", dest="runlocal",
        default=False, help="Run from current directory.")
    (options, args) = parser.parse_args()

    if options.runlocal:
        pglobals.image_dir =  os.path.join(os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])), ".."), "images")
        pglobals.bin_dir = os.path.abspath(os.path.dirname(sys.argv[0]))
        pglobals.glade_dir = os.path.abspath(os.path.dirname(sys.argv[0]))
   
    a = gnome15.g15_config.G15Config()
    a.run()
