#!/usr/bin/env python
 
import pynotify

pynotify.init("G15 Applet")
        
activate_notify = pynotify.Notification("G15", "Current macro profile changed XX")
activate_notify.set_urgency(pynotify.URGENCY_CRITICAL)
activate_notify.set_timeout(10000) # 10 seconds - Ignored now
activate_notify.set_category("device")
#activate_notify.set_icon_from_pixbuf(self.logo_pixbuf)
try:
    self.activate_notify.show()
except:
    pass
 