#!/bin/sh
set -e
# Automatically added by dh_installudev
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/udev/rules.d/z60_lg4l-linux.rules" ]; then
		if [ "`md5sum \"/etc/udev/rules.d/z60_lg4l-linux.rules\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' lg4l-linux | sed -n -e \"\\\\' /etc/udev/rules.d/z60_lg4l-linux.rules '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			rm -f "/etc/udev/rules.d/z60_lg4l-linux.rules"
		fi
	fi
fi
# End automatically added section
