#!/bin/sh
set -e

if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi

if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall @appname@
	if grep -qs '^@appname@$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^@appname@$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi

if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/hicolor
fi

