#!/usr/bin/env python
 
#        +-----------------------------------------------------------------------------+
#        | GPL                                                                         |
#        +-----------------------------------------------------------------------------+
#        | Copyright (c) Brett Smith <tanktarta@blueyonder.co.uk>                      |
#        |                                                                             |
#        | This program is free software; you can redistribute it and/or               |
#        | modify it under the terms of the GNU General Public License                 |
#        | as published by the Free Software Foundation; either version 2              |
#        | of the License, or (at your option) any later version.                      |
#        |                                                                             |
#        | This program is distributed in the hope that it will be useful,             |
#        | but WITHOUT ANY WARRANTY; without even the implied warranty of              |
#        | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
#        | GNU General Public License for more details.                                |
#        |                                                                             |
#        | You should have received a copy of the GNU General Public License           |
#        | along with this program; if not, write to the Free Software                 |
#        | Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. |
#        +-----------------------------------------------------------------------------+

'''
Provides a panel indicator that can be used to control and monitor the Gnome15
desktop service (g15-desktop-service). It will display a list of currently active
screens on activation, and allow the configuration UI to be launched (g15-config)
'''

import sys
import pygtk
pygtk.require('2.0')
import gtk
import os
import appindicator
import gconf
import traceback
from threading import RLock

# Logging
import logging
logging.basicConfig()
logger = logging.getLogger()

# Allow running from local path
path = os.path.join(os.path.abspath(os.path.dirname(sys.argv[0])), "..", "src", "main", "python")
if os.path.exists(path):
    sys.path.insert(0, path)

# This block MUST be before the imports of the gnome15 modules
import dbus
import gobject
gobject.threads_init()
import dbus
from dbus.mainloop.glib import DBusGMainLoop
from dbus.mainloop.glib import threads_init
threads_init()
DBusGMainLoop(set_as_default=True)

import gnome15.g15globals as g15globals
import gnome15.g15service as g15service
import gnome15.g15screen as g15screen
import gnome15.util.g15convert as g15convert
import gnome15.g15desktop as g15desktop

class G15Indicator(g15desktop.G15GtkMenuPanelComponent):
    
    def __init__(self):
        g15desktop.G15GtkMenuPanelComponent.__init__(self)
        
    def create_component(self):
        
        item = gtk.MenuItem("Preferences")
        item.connect("activate", self.show_configuration)
        self.menu.append(item)
        
        item = gtk.MenuItem("About Gnome15")
        item.connect("activate", self.about_info)
        self.menu.append(item)
        
        self.menu.append(gtk.MenuItem())
        
        self.indicator = appindicator.Indicator("gnome15",
                               self.get_icon_path("logitech-g-keyboard-panel"), 
                               appindicator.CATEGORY_HARDWARE)
        self.indicator.set_status (appindicator.STATUS_ACTIVE)
        self.indicator.set_menu(self.menu)
        
    def clear_attention(self):
        self.remove_attention_menu_item()
        if self.conf_client.get_bool("/apps/gnome15/indicate_only_on_error"):
            self.indicator.set_status (appindicator.STATUS_PASSIVE)
        else:
            self.indicator.set_status (appindicator.STATUS_ACTIVE)
        
    def attention(self, message = None):
        self.indicator.set_status (appindicator.STATUS_ATTENTION)
        
    def icons_changed(self):
        self.indicator.set_icon(self.get_icon_path([ "logitech-g-keyboard-panel", "logitech-g-keyboard-applet" ]))        
        self.indicator.set_attention_icon(self.get_icon_path([ "logitech-g-keyboard-error-panel", "logitech-g-keyboard-error-applet" ]))
    
# run it in a gtk window
if __name__ == "__main__":
    try :
        import setproctitle
        setproctitle.setproctitle(os.path.basename(os.path.abspath(sys.argv[0])))
    except:
        pass
    
    if g15desktop.get_desktop() == "gnome-shell":
        sys.stderr.write("Indicator is not supported in GNOME Shell, use the GNOME Shell extension instead")
        sys.exit(1)
    
    G15Indicator().start_service()   
    gtk.main()