#!/bin/sh
# postinst script for g19d
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure) 
    
if [ -x "/etc/init.d/g19d" ]; then
	update-rc.d g19d defaults >/dev/null
fi

	
# Don't try and start the service, Python is not completely setup yet
# 	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
#		invoke-rc.d g19d start || exit $?
#	else
#		/etc/init.d/g19d start || exit $?
#	fi

if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  g19d.public
fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
