#!/bin/sh

NAME=lg4l
PACKAGE_NAME=$NAME-dkms

CVERSION=`dpkg-query -W -f='${Version}' $PACKAGE_NAME | cut -d\: -f2`

ARCH=`dpkg --print-architecture`
case $ARCH in
       amd64)
               ARCH="x86_64"
               ;;
       lpia)
               ARCH="i686"
               ;;
       i386)
               ARCH="i686"
               ;;
       armel)
               ;;
       *)
               echo "WARNING: potentially unsupported arch: $ARCH"
               ARCH="$ARCH"
               ;;
esac



case "$1" in
        configure)
                for POSTINST in /usr/lib/dkms/common.postinst /usr/share/$PACKAGE_NAME/postinst; do
                        if [ -f $POSTINST ]; then
                                $POSTINST $NAME $CVERSION /usr/share/$PACKAGE_NAME $ARCH $2
                                exit $?
                        fi
                        echo "WARNING: $POSTINST does not exist."
                done
                echo "ERROR: DKMS version is too old and $PACKAGE_NAME was not"
                echo "built with legacy DKMS support."
                echo "You must either rebuild $PACKAGE_NAME with legacy postinst"
                echo "support or upgrade DKMS to a more current version."
                exit 1
        ;;

        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)
                echo "postinst called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac

# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	if [ -e "/etc/udev/rules.d/z60_lg4l.rules" ]; then
		echo "Preserving user changes to /etc/udev/rules.d/40-lg4l.rules ..."
		if [ -e "/etc/udev/rules.d/40-lg4l.rules" ]; then
			mv -f "/etc/udev/rules.d/40-lg4l.rules" "/etc/udev/rules.d/40-lg4l.rules.dpkg-new"
		fi
		mv -f "/etc/udev/rules.d/z60_lg4l.rules" "/etc/udev/rules.d/40-lg4l.rules"
	fi
fi
# End automatically added section

