.TH LG4l 8 2011-06-06 "lg4l" "Logitech Drivers For Linux"
.SH NAME
r5u870 \-   Logitech Drivers For Linux
.SH DESCRIPTION
.I  lg4l
 Kernel driver for a range of Logitech G series keyboards, including
 the G13, G15, G19 and G110.
 046d:c229	Logitech G19				hid-g19
 046d:c222	Logitech G15 (version 1)	hid-g15
 046d:c227	Logitech G15 (version 2)	hid-g15
 046d:c21c	Logitech G13				hid-g13
 046d:c225	Logitech G110				hid-g110
 
.TP
.B More information
lg4l maintainer: http://wiki.mediati.org/R5u870
lg4l-dkms maintainer: https://github.com/ali1234/lg4l
.SH AUTHORS
Alistair Buxton

