.\" Process this file with
.\" groff -man -Tascii g15-indicator.1
.\"
.TH g15-indicator 1
.SH NAME
g15-indicator \- Starts Gnome15 in indicator mode
.SH SYNOPSIS
.B g15-indicator [-c] 
.SH DESCRIPTION
.B g15-indicator
Starts the Gnome15 desktop service in 
.I indicator mode. 
Gnome15 is a suite of applications and plugins that provide
integration of the Logitech G series keyboards into the 
GNOME desktop environment.

This service is responsible for connecting to the underlying
service appropriate for the hardware (i.e. g15daemon or g19d),
managing and running the plugins, displaying the plugin's
output on the LCD, delivering key events to X when macro
keys are activated.

The first time Gnome15 is used, you will be prompted for
which driver to use (additional packages may be required
for your hardware). 
.SH OPTIONS
.IP -c
Force the first-run configuration dialog to appear, allowing
choice of which driver to use.
.SH BUGS
Indicator menu items are not added for screens on earlier
versions of the indicator applet.
.SH AUTHOR
Brett Smith <tanktarta@blueyonder.co.uk>
.SH "SEE ALSO"
.BR g15-config (1),
.BR g15-macros (1)