.\" Process this file with
.\" groff -man -Tascii g15-macros.1
.\"
.TH g15-macros 1
.SH NAME
g15-macros \- Configure Logitech G keyboard macros
.SH SYNOPSIS
.B g15-macros [-c] 
.SH DESCRIPTION
.B g15-macros
Starts the 
.B Gnome15  
Logitech G keyboard macro tool.
It allows you to create multiple macro profiles
which may be activated either manually, or
when a particular window becomes active.

Each profile has 3 memory banks that may be activated
using the
.B M-Key
on the keyboard. If supported by the hardware, you can also
assign keyboard backlight colours to each memory bank 
within the profile.

The number of assignable macros differs depending on the hardware,
but you will probably be assigning macros to the 
.B G-Keys

For the macros to actually work, you will also need to run
the
.I Gnome15 Desktop Service
in the background. To do this, either run the
.B g15-indicator
command, or add the
.B Gnome15 Applet
to a panel. 
.SH OPTIONS
.IP -c
Force the first-run configuration dialog to appear, allow
choice of which driver to use (additional packages may be required
for your hardware).
.SH AUTHOR
Brett Smith <tanktarta@blueyonder.co.uk>
.SH "SEE ALSO"
.BR g15-indicator (1),
.BR g15-config (1)