#!/bin/sh
# Copyright (C) 2002-2005 Flavio Stanchina
# Copyright (C) 2005-2006 Aric Cyr
# Copyright (C) 2007 Mario Limonciello

CVERSION=`dpkg-query -W -f='${Version}' lg4l-dkms | awk -F "-" '{print $1}' | cut -d\: -f2`



case "$1" in
	configure)
		echo "Adding Module to DKMS build system"
		dkms add -m lg4l -v $CVERSION > /dev/null
		echo "Doing initial module build"
		dkms build -m lg4l -v $CVERSION > /dev/null
		echo "Installing initial module"
		dkms install -m lg4l -v $CVERSION --force > /dev/null
		echo "Done."
	;;
esac
